# Generated by Django 6.0 on 2026-02-12 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('sender_role', models.CharField(default='laptop', max_length=20)),
                ('status', models.CharField(default='waiting', max_length=20)),
            ],
        ),
    ]
