# Generated by Django 6.0 on 2026-02-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sender_role',
            field=models.CharField(default='Laptop or Desktop', max_length=20),
        ),
    ]
