# Generated by Django 5.2.8 on 2026-03-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_session_sender_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('file_sent', 'file_sent'), ('expired', 'expired')], default='waiting', max_length=20),
        ),
    ]
