# Generated by Django 5.2.8 on 2026-04-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('file_sent', 'file_sent'), ('expired', 'expired'), ('file_receive', 'file_receive')], default='waiting', max_length=20),
        ),
    ]
