# Generated by Django 5.2.8 on 2026-04-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_transferfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferfile',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
